#ifndef CONFIG_H
#define CONFIG_H

#define MAX_FILESYSTEMS 12
#define MAX_FILE_DESCRIPTORS 512

#define MAX_FILENAME_PATH 64

#define MAX_PROCESSES 256
#define MAX_PROGRAM_ALLOCATIONS 1024

#define MAX_ISR80H_COMMANDS 1024

#endif
